### ISSUE TITLE
401 Error Code

### ISSUE THREAD

**Issue by NotoriousBUG** [cjekel/tindetheus#11]
Using the docker setup, I created a config.txt in the docked machine, but even using the technique shown  [here](http://www.joelotter.com/2015/05/17/dj-khaled-tinder-bot.html ), and correctly getting the Tinder Facebook Token, an error pynder.errors.RequestError: Couldn't authenticate request status code: 401 is raised.

**Comment by cjekel** [comment]
Let me know what this gives you

```python
import requests
facebook_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
USER_AGENT = "Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)"
HEADERS = {
    'app_version': '6.9.4',
    'platform': 'ios',
    "content-type": "application/json",
    "User-agent": USER_AGENT,
    "Accept": "application/json"
}
new_url = 'https://api.gotinder.com/v2/auth/login/facebook'
new_data = {"token": facebook_token}
r_new = requests.post(new_url, headers=HEADERS, json=new_data)
print(r_new.status_code)
print(r_new.json())
```

In my case I get something like
```python
200
{'meta': {'status': 200}, 'data': {'_id': 'xxxxx', 'api_token': 'xxxxxxx', 'refresh_token': 'xxxxxxx', 'is_new_user': False}}
```
where api_token is your X-Auth-Token.

If you get a 401 here, you probably don't have the correct facebook_token.

**Comment by NotoriousBUG** [comment]
Hi @cjekel ,

I tried to double check what I wrote above, just to be sure and don't waste anyone's time.

I tried to access a https://graph.facebook.com/me?access_token=xxxx with the token I collected from the SSL Proxy but even that gives me a 401 error.

I suppose it's an issue on gathering the FB Access Token. Is there any other method? I accessed the auth folder on the proxy and copied the token, whose format is the same as described in your guide.

Hoping to hear from you soon, bye.

**Comment by cjekel** [comment]
That url works for me with my token. The proxy _should_ still work, but I haven't been up to date with things.

You can try to auth with phone/sms https://github.com/fbessez/Tinder/blob/master/phone_auth_token.py

I think that will return the X-Auth-token with this format ```xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx```

**Comment by NotoriousBUG** [comment]
Hi @cjekel 

Tried the process you have indicated me but error code changed from 401 to 190

message | "Invalid OAuth access token."
-- | --
type | "OAuthException"
code | 190

**Comment by NotoriousBUG** [comment]
Followed the procedure you described, it works. Thank you, have a nice day.
