### ISSUE TITLE
Tindetheus only works with Tensorflow 1.15 mac OSX 

### ISSUE THREAD

**Issue by holdenjrussell** [cjekel/tindetheus#19]
Wanted to make a quick callout. I was only able to get tindetheus working on a mac using tensorflow1.15 which has GPU support.

pip install --pre "tensorflow==1.15.*"

**Comment by cjekel** [comment]
Facenet currently doesn't support tensorflow 2.0 on all systems. I'll eventually bring it up to 2.0, but I first wanted to clean a few things up. I started this in my facenet fork, but it will take some time.

In the meantime I changed the tensorflow requirement to ```< 2.0.0```.
