### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by VikashKothary** [cjekel/tindetheus#22]
A requirements.txt file will all the dependencies would help. Here's what I had so far
```
pip
jupyter
setuptools
tindetheus
opencv-python
pynder
```

**Comment by cjekel** [comment]
You are right, this is currently dependency hell right now.

I think this may be everything, and it might be possible to remove a few of these.
```
future>=0.16.0
h5py
imageio>=2.4.0
joblib>=0.13.0
jupyter
matplotlib>=2.0.0
numpy>=1.14.0
opencv-python>=3.4.2
pandas>=0.21.0
pynder>=0.0.14
Pillow
pip
psutil
requests
scikit-image>=0.13.1
scikit-learn>=0.19.0
scipy>=1.0.0
setuptools>=38.6.0
tensorflow<=1.15
```

**Comment by cjekel** [comment]
Need to check whether opencv-python is actually needed. New conda environment without this seemed to work fine.

**Comment by VikashKothary** [comment]
Wow that was a quick turn around. I see you've added a requirements.txt here: https://github.com/cjekel/tindetheus/commit/2902ab03b15d199ce2f6e780ec90b27464f88311. 

Shall we close this issue?

**Comment by cjekel** [comment]
Let's keep it open for now. I commented out opencv-python when it should be there.

Also I want to update the instructions to mention requirements.txt for setting up a virtual environment.

Anyone who wants to chip in can send a PR for these things. 

---

It's nice to see all the attention this project has gotten this weekend. For awhile I thought this work was dead. 

Simple issues like this help make the project better. You can always reach out to me if you have any questions or find any issues. 

So thanks to everyone for chiming in and helping improve this project.

**Comment by VikashKothary** [comment]
It might be worth reopening this issue. I didn't realise you use conda as a package manager. As such, it might be worth moving to an `environment.yml` file over a `requirements.txt`. It'll reduce the change of issues if everyone uses the same environment.

**Comment by cjekel** [comment]
I'm not sure if opencv-python is available with conda. I could go either way.

Can you have a enviorment.yml that fetches certain projects from pypi if they aren't on conda?

Maybe I should change the instructions to use pyenv as you did in the makefile?

**Comment by VikashKothary** [comment]
@cjekel Both those sound good. I'll prefer to use the tools you are using to minimise 'works on my machine' bugs. So using `pyenv` in the Makefile makes sense.
Regarding conda, you can also get it pull from pip as well. So I'm happy with either. We should just be consistent imo.
