### ISSUE TITLE
Pynder submodule

### ISSUE THREAD

**Issue by VikashKothary** [cjekel/tindetheus#24]
Just a thought. You should use 'git submodules' to include the specific commit of the pynder repo you use in this project.  It's easier to maintain and can be used in the requirements.txt.

And it there a reason you're not using the latest version of the library?

**Comment by cjekel** [comment]
Thanks for the suggestion. This is the first I'm hearing about git submodules, I'll check it out.

So pynder on [pypi](https://pypi.org/project/pynder) is a few commits behind the maintainers/creators source. Then there is my PR for the updated authentication API. I rolled the minor version in that, hoping it would help avoid confusion.

I'll have to look into how this works. If it's easy for you to add, feel free to send a PR. 

This could probably also be done with facenet, which right now is hard forked into this library. I've always thought this was sloppy. I'm in no hurry, but eventually facenet will be ported to tensorflow>=2.0.
