### ISSUE TITLE
Use Environment Variables

### ISSUE THREAD

**Issue by VikashKothary** [cjekel/tindetheus#32]
Using environment variables and `.env` files over a `config.txt` file will make the program more portable and works better with Docker. 

What do you think?

**Comment by cjekel** [comment]
Will the .env file override environment variables when present?

My config.txt parsing is terrible, and has created a number of issues. So alternatively setting the environment variables (or having a .env file) sounds like a nice improvement.

**Comment by VikashKothary** [comment]
Yes for the program. No for the system. 
A `.env` is just a list of environment variables. When the program is run, they are loaded into the shell for that program.  The environment variables in the rest of the system stay the same.

**Comment by cjekel** [comment]
https://github.com/cjekel/tindetheus/commit/3eaf9f241628371660a7a3ffea6071ebba1b22f2 closed
