### ISSUE TITLE
tf.train.import_meta_graph deprecated in favor of tf.compat.v1.train.import_meta_graph 

### ISSUE THREAD

**Issue by m0rg1an** [cjekel/tindetheus#33]
Hi- ran into an issue while running 'tindetheus like'. The runtime was 'killed' due to a deprecated facenet function.

`root@ce568c388715:/tinder# tindetheus like

... Loading the facenet model ...
... be patient this may take some time ...
WARNING:tensorflow:From /tindetheus/tindetheus/tindetheus.py:144: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-15 03:22:26.767805: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-15 03:22:26.807672: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400065000 Hz
2020-03-15 03:22:26.808252: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4bf7440 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-15 03:22:26.808483: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Hello  Morgan
You have browsed 167 Tinder profiles.
Model directory: 20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
WARNING:tensorflow:From /tindetheus/tindetheus/facenet_clone/facenet.py:381: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

Killed`

**Comment by cjekel** [comment]
That warning shouldn't have killed tindetheus. 

Does this happen every time you run? Is loading the facenet model filling up the memory limit for the container?

**Comment by cjekel** [comment]
@m0rg1an Did you end up getting this working, or are you still running into issues? Are you running the latest docker build?

**Comment by m0rg1an** [comment]
Thanks for the follow up. It's up and running for me now- really impressive app you've built here.  The only thing, pynder isn't is erroring out with the facebooktoken, so I'm manually inputing the xauthtoken. As a quick fix, I'll probably just edit the authentication module in your code directly, so I can use my fb credentials.

**Comment by m0rg1an** [comment]
By the way, I think you your diagnosis about the memory limitation was right. I was initially runnning the model on a t2.micro aws linux, upgraded to t2.large and the model now runs like a charm. Thanks again!
