### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Gusanito2D2** [cjekel/tindetheus#45]
When I enter the command: "tindetheus browse" after running the docker I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/tindetheus", line 11, in <module>
    load_entry_point('tindetheus', 'console_scripts', 'tindetheus')()
  File "/tindetheus/tindetheus/tindetheus.py", line 273, in command_line_run
    raise('ERROR: No facebook or tinder token has been set.'
TypeError: exceptions must derive from BaseException

I've followed all steps of the guide and I have a .env file with my facebook access token into the tinder folder.

**Comment by cjekel** [comment]
I think I ran into this on docker(or linux) as well at some point, but I can't reproduce right now. 

In your current working directory in docker, when you run ```cat .env``` make sure you see no spelling mistakes in these variable names ```TINDER_AUTH_TOKEN="TODO"``` or ```FACEBOOK_AUTH_TOKEN="TODO"```

Also take a look at these values in a python/ipython console:
```python
import tindetheus
tindetheus.config.TINDER_AUTH_TOKEN
tindetheus.config.FACEBOOK_AUTH_TOKEN
```

**Comment by Gusanito2D2** [comment]
I run "cat .env" in docker but it says:
cat: .env: No such file or directory
and effectively there's no file called .env in this folder and there's no other files, I entered the "ls" command but appears to be empty.

**Comment by cjekel** [comment]
The mount command must not be working

```bash
docker run -it -v /absolute/path/to/your/tinder/:/tinder cjekel/tindetheus
```

where you change ```/absolute/path/to/your/tinder/``` to the folder that contains such items? 

Are you using docker with windows 10?

**Comment by Gusanito2D2** [comment]
I also did that when following the GETTING_STARTED guide
I am on ubuntu 19.10 (64 bits)
I can't install docker in my Windows 10 because of version incompatibility (docker needs a Windows Insider Preview version but I don't want to modify my OS)

**Comment by cjekel** [comment]
Hmm not sure why the volumes is failing you. I asked about windows since I think they have had these issues with windows as well.

Since you are on Ubuntu (which is what the docker container is running), installing locally should be easy. From the [Dockerfile](https://github.com/cjekel/tindetheus/blob/master/Dockerfile)

```bash
apt-get install git vim nano python3-dev python3-numpy python3-scipy python3-pip python3-venv wget perl unzip libsm6 libxrender1
git clone https://github.com:cjekel/tindetheus.git
cd tindetheus && python3 -m pip install --upgrade pip && python3 -m pip install --upgrade -r requirements.txt
```
which should give you the bash command tindetheus

**Comment by Gusanito2D2** [comment]
I do that and I get this in the latest lines after running "sudo python3 -m pip install --upgrade -r requirements.txt":

`running build_ext
    building 'imagecodecs._aec' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/imagecodecs
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iimagecodecs -I/usr/include/python3.7m -I/usr/local/lib/python3.7/dist-packages/numpy/core/include -c imagecodecs/_aec.c -o build/temp.linux-x86_64-3.7/imagecodecs/_aec.o
    In file included from /usr/include/python3.7m/numpy/ndarraytypes.h:1822,
                     from /usr/include/python3.7m/numpy/ndarrayobject.h:12,
                     from /usr/include/python3.7m/numpy/arrayobject.h:4,
                     from imagecodecs/_aec.c:598:
    /usr/include/python3.7m/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    imagecodecs/_aec.c:602:10: fatal error: libaec.h: No such file or directory
      602 | #include "libaec.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5darek0d/imagecodecs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cw7nbvzk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-5darek0d/imagecodecs/
`

**Comment by Gusanito2D2** [comment]
I get the same error.
I also tried it in Windows 10, doing all steps of your guide [https://jekel.me/2018/How-to-install-tindetheus-on-windows-10-to-automatically-like-users-on-tinder/](url) and configuring the "tinder" folder but nothing appears when I enter "tindetheus browse"

**Comment by cjekel** [comment]
To clarify, you get this following error after installing on ubuntu?
```
Traceback (most recent call last):
File "/usr/local/bin/tindetheus", line 11, in
load_entry_point('tindetheus', 'console_scripts', 'tindetheus')()
File "/tindetheus/tindetheus/tindetheus.py", line 273, in command_line_run
raise('ERROR: No facebook or tinder token has been set.'
TypeError: exceptions must derive from BaseException
```

What you should see after running ```tindetheus browse``` is ```hello $YOUR_NAME```, then a profile should pop up.

It seems that everything is going wrong, and I'm happy to keep answering questions if it helps you troubleshoot.

**Comment by Gusanito2D2** [comment]
Yes, that is the error I get on ubuntu after running "tindertheus browse". 
On windows I run the same command but nothing is returned in the cmd console.

**Comment by cjekel** [comment]
> Yes, that is the error I get on ubuntu after running "tindertheus browse".

Make sure your .env is setup in the current working directory before running tindetheus browse. This .env will contain the environment variable which contains your tinder token, allowing you to login.

**Comment by Gusanito2D2** [comment]
Yes, it is in the tinder folder, I used the facebook auth token and deleted the line of the tinder token

**Comment by cjekel** [comment]
You can try exporting the environment variable manually before running tindetheus
```bash
export FACEBOOK_AUTH_TOKEN="your-private-token-here"
tindetheus browse
```
which _should_ avoid the  ```raise('ERROR: No facebook or tinder token has been set.'```


If this doesn't work, we'll have to debug the config.py, specifically why these lines aren't working
```python
TINDER_AUTH_TOKEN = os.getenv('TINDER_AUTH_TOKEN', None)
FACEBOOK_AUTH_TOKEN = os.getenv('FACEBOOK_AUTH_TOKEN', None)
```

**Comment by Gusanito2D2** [comment]
I did that and it gives me another error:

`Traceback (most recent call last):
  File "/home/osboxes/.local/bin/tindetheus", line 11, in <module>
    load_entry_point('tindetheus', 'console_scripts', 'tindetheus')()
  File "/home/osboxes/tindetheus/tindetheus/tindetheus.py", line 278, in command_line_run
    retries=defaults['retries'])
  File "/home/osboxes/tindetheus/tindetheus/tindetheus.py", line 80, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/home/osboxes/tindetheus/tindetheus/tinder_client.py", line 89, in __init__
    self.session = self.login(facebook_token, x_auth_token)
  File "/home/osboxes/tindetheus/tindetheus/tinder_client.py", line 127, in login
    XAuthToken=x_auth_token)
  File "/home/osboxes/.local/lib/python3.7/site-packages/pynder/session.py", line 18, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/home/osboxes/.local/lib/python3.7/site-packages/pynder/api.py", line 41, in auth
    raise errors.RequestError(err)
pynder.errors.RequestError: Couldn't authenticate request status code: 401
`

**Comment by cjekel** [comment]
This normally means your token has expired, or you are unable to login with that token. I think the ```FACEBOOK_AUTH_TOKEN``` only last a limited number of hours, where the other tokens could last longer.

**Comment by Gusanito2D2** [comment]
I used and updated token with an expiration date of within 2 months

**Comment by cjekel** [comment]
Are you sure you are using the right token? If your token is of this form ```xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx``` you can try setting the ```TINDER_AUTH_TOKEN```

```bash
unset FACEBOOK_AUTH_TOKEN  # this removes FACEBOOK_AUTH_TOKEN if it's assigned 
export TINDER_AUTH_TOKEN="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
tindetheus browse
```

**Comment by Gusanito2D2** [comment]
The facebook token I have is not in that format with the "-". I don't know where could I find it in the right format. I used this guide: [https://elfsight.com/blog/2017/10/how-to-get-facebook-access-token/](url)

**Comment by cjekel** [comment]
I tried yesterday, and was unable to auth via facebook. This method shows both tokens https://jazzytomato.com/hacking-tinder-2/ 

Also if you don't mind getting the X-Auth-token, people have reported success with this https://github.com/fbessez/Tinder/blob/master/phone_auth_token.py

**Comment by Gusanito2D2** [comment]
I don't have iOS, the script and this guide are for MacOS and iOS

**Comment by Gusanito2D2** [comment]
Solved, now it works. Thank you!

**Comment by Gusanito2D2** [comment]
I used this guide to get the token instead
[https://hackernoon.com/auto-tinder-train-an-ai-to-swipe-tinder-for-you-dw23c3zj7](url)
