### ISSUE TITLE
Config.txt issue

### ISSUE THREAD

**Issue by robpot891** [cjekel/tindetheus#8]
So I was getting the error message again saying 401 auth error.

The issue only happens when in a folder with a config.txt. If you launch tindetheus from an empty folder it starts fine. Thought I'd let you know.

**Comment by cjekel** [comment]
Thanks for letting me know.

I have a couple questions for you

Are you using the ```tindetheus.__version == '0.4.1``` ?

Do you happen to have any quotes around your token in the config.txt file? It should just be
```facebook_token = xxxxxxxxxxxxxxxxxxxx```

**Comment by robpot891** [comment]
Yep I had the token as a string and when I changed that everything worked smoothly.
